### PR TITLE
added 1.17 and 1.18 and more

### PR DESCRIPTION
**Pull request by Sertonix**
- renamed 1.16 to 1.16.5:
  '-> added teammsg,tm,tp,help,list command
  '-> removed structureSaveDestination gamerule
- added 1.17-1.17.1 and 1.18-1.18.1
- added support for item modifiers
- replaced fixed base version with the last version in the array
- commands now come from the last version with set commands
- the version "snapshot" is currently unused (maybe add support for 
snpshots?)

### CODE REVIEW

**Comment by MrAn0nym** [comment]
@jan00bl  Merge when?

**Comment by jan00bl** [comment]
I planned to test it and merge it tommorow. I am currently pretty busy with university stuff.

**Comment by MrAn0nym** [comment]
> I planned to test it and merge it tommorow. I am currently pretty busy with university stuff.

👍🏻

**Review by jan00bl — APPROVED** [review]
Thank you so much for updating everything to 1.18 ^^
Sorry that I waited so long to look at this PR 😅
I try to keep it updated for 1.19, but a bit of help is always welcome c:

**Pull request merged**
